@host = https://localhost:7006

POST {{host}}/Auth/register
Content-Type: application/json

{
  "firstName": "string",
  "lastName": "string",
  "email": "string",
  "password": "string",
  "token":"ss"
}